// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    '// Read more': https://github.com/vuejs/vue-next/pull/3399
    Card: typeof import('./src/components/Card.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
  }
}

export { }
